checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: vendor/bin/tester tests -s -d zend_extension=xdebug.so --coverage coverage.xml --coverage-src src
                coverage:
                    file: coverage.xml
                    format: php-clover
    deployment:
        -
            commands:
	            - curl https://github.com/romanmatyus/DateInterval | grep -o '<img[ ]*src="[^"]*"' | grep -o '"[^"]*"' | grep -o '[^"]*' | grep https://camo.githubusercontent.com | xargs -L1 curl -X PURGE
